### PR TITLE
`gefs2lbc_para` error return codes

### PR DESCRIPTION
**Pull request by zmoon**
Currently, when there is a recognized error, the program still returns with return code 0. See discussion in https://github.com/NOAA-EMC/AQM/issues/88.

### CODE REVIEW

**Comment by zmoon** [comment]
@ytangnoaa should we also have the `check` exit with nonzero rc as well?

https://github.com/noaa-oar-arl/AQM-utils/blob/153d34971f44673aabe1727e43cbb65253a19e31/sorc/gefs2clbcs_para.fd/gefs2lbc_para.f90#L679-L687

Also was curious about that `end` that looks to be extra.

**Comment by ytangnoaa** [comment]
Need update sorc/gefs2clbcs_para.fd/gefs2lbc_para.f90

**Comment by chan-hoo** [comment]
@ytangnoaa, Is this PR ready for review now?

**Comment by ytangnoaa** [comment]
I updated the code with changed error return value. The two scripts were also updated.

**Comment by ytangnoaa** [comment]
> @ytangnoaa, Is this PR ready for review now?
Yes, you can find the change in 
https://github.com/noaa-oar-arl/AQM-utils/commit/bcbae88ef59af2db064c1b672af8d81e9a855e03

**Comment by chan-hoo** [comment]
@ytangnoaa, this pr has conflicts. Please resolve them.

**Comment by ytangnoaa** [comment]
> @ytangnoaa should we also have the `check` exit with nonzero rc as well?
> 
> https://github.com/noaa-oar-arl/AQM-utils/blob/153d34971f44673aabe1727e43cbb65253a19e31/sorc/gefs2clbcs_para.fd/gefs2lbc_para.f90#L679-L687
> 
> Also was curious about that `end` that looks to be extra.

Changed with non-zero error return et al

**Comment by ytangnoaa** [comment]
> @ytangnoaa, this pr has conflicts. Please resolve them.

@zmoon could you help resolve the PR conflict?

**Review by chan-hoo — APPROVED** [review]

**Pull request merged**
