### PR TITLE
deleted unused files with convert_airnow_csv and two setup files for bias correction

### PR DESCRIPTION
**Pull request by JianpingHuang-NOAA**
1) to delete the unused files for convert_airnow_csv
2) to delete unused setup files for bias correction 

### Machines/Platforms:

- WCOSS2
 
### Test cases: 

- [ ] Build test
- [ ] Test with applications
  - [ ] UFS SRW App
  - [ ] RRFS Workflow
  - [x] Others:

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA is there any testing that goes on for this to know it doesn't break anything?

**Comment by BrianCurtis-NOAA** [comment]
I am weary about just removing code to meet EE2 standards if we aren't separating it out from a develop branch. Does this deleted code get used outside of operational needs?

**Comment by JianpingHuang-NOAA** [comment]
Those files were created for temporary test. We should  delete them. Removing those files will not affect research community.

**Comment by BrianCurtis-NOAA** [comment]
There should not be temporary files stored inside a development repository. What testing was done with this? It says others, but i don't know what others is.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  Can you help us to complete the review?  Thanks !

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA @BrianCurtis-NOAA, Currently, the `bias_correction` task using `convert_airnow_csv` is only available on WCOSS2. This is because the airnow data is only available on WCOSS2. The community users do not run the production tasks such as `bias_correction` and `post_stat` on other machines. Hope my comment helps.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo Yes, that is correct.

**Comment by BrianCurtis-NOAA** [comment]
@chan-hoo @JianpingHuang-NOAA Just wanted to confirm, that these deletions are never going to be needed again. If they are, then we should have a production branch and do this work there instead.

**Comment by JianpingHuang-NOAA** [comment]
@BrianCurtis-NOAA  Yes

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
